### ISSUE TITLE
Is ResNet50 weights or pre-trained models available?

### ISSUE THREAD

**Issue by cjiang2** [nqanh/video_2_command#1]
Hello, first of all, this is a very interesting work combing captioning into the robotic application.

I am wondering if any pre-trained models are available for inference? Or would you mind providing the missing pre-extracted features with ResNet50 so that it will be easier to train a model on my own?

Thanks in advance!

Edit: From my review of the code, it seems that the part of the code for extracting image features and packing up (images, captions) into a single pkl file is missing.

**Comment by nqanh** [comment]
I have added the link for the pre-extracted features. 
Best,

**Comment by cjiang2** [comment]
Thank you with the updated features. I'll close up the issue for now and update if I have more questions.

**Comment by ccmoe** [comment]
According to the files provided by the author and zonetrooper 32, it's ready to run. Thank you very much. I'll close this issue.
