### ISSUE TITLE
How do I get the IIT-V2C dataset

### ISSUE THREAD

**Issue by laohuijiadezhu** [nqanh/video_2_command#5]
Hello, Prof. Nguyen. I want to follow this work. My access was denied on Google drive.
How do I get the IIT-V2C dataset? Thanks.

**Comment by nqanh** [comment]
Hi, thanks for your interest. I have added One Drive link to the download page. Hope it works for you.

**Comment by laohuijiadezhu** [comment]
Thank you very much for your reply. This link solves my problem very well. Benefit a lot.
